add typecheck-code.py (mypy) to build process

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -21,7 +21,7 @@ jobs:
           - name: macos-3.13-skip-exe
             python-version: "3.13"
             os: macos-latest
-          - name: linux-3.13-lint-update-help-skip-exe
+          - name: linux-3.13-typecheck-lint-update-help-skip-exe
             python-version: "3.13"
             os: ubuntu-latest
           - name: linux-3.12-pytype-skip-exe
@@ -97,7 +97,7 @@ jobs:
           python -m pip install --upgrade pip setuptools wheel
           echo "::endgroup::"
           echo "::group::Run pip install .[test] flake8 Flake8-pyproject"
-          pip install .[test] flake8 Flake8-pyproject
+          pip install .[test] mypy flake8 Flake8-pyproject
           echo "::endgroup::"
       - name: Run full tests (unless -skip-exe)
         if: ${{ !contains(matrix.name, '-skip-exe') }}
@@ -141,6 +141,15 @@ jobs:
           SEVERITY=warning
           ${{ startsWith(matrix.name, 'windows-') }} && SEVERITY=notice
           [ $FAILED -eq 0 ] || echo "::$SEVERITY::try-examples.py failed with exit code $FAILED (XFAIL 'Graphviz not built with triangulation library' on Windows cbuild)"
+        shell: bash
+      - name: Run typecheck-code.py (if -typecheck)
+        if: ${{ contains(matrix.name, '-typecheck') }}
+        run: |
+          echo "::group::Run typecheck-code.py"
+          FAILED=0
+          python typecheck-code.py || FAILED=$?
+          echo "::endgroup::"
+          [ $FAILED -eq 0 ] || echo "::warning::typecheck-code.py failed with exit code $FAILED"
         shell: bash
       - name: Run lint-code.py (if -lint)
         if: ${{ contains(matrix.name, '-lint') }}
